#!/bin/bash
### BEGIN INIT INFO
# Provides: userdataExecutor
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: User description here
### END INIT INFO
# description: uCloud server userdata execution script

. "$(dirname "${BASH_SOURCE[0]}")/common"

for RVM_IP in $(get_dhcpopt dhcp-server-identifier)
do
       echo "Sending userdata request to RVM at $RVM_IP"
       curl -Ls -retry 3 -m 20 http://$RVM_IP/latest/user-data -o /tmp/userdata
       chmod 755 /tmp/userdata

       if [ -s /tmp/userdata ]
       then
              if [ ! -d /var/backups ]
              then
                     mkdir /var/backups
              fi
              if [ -f /var/backups/userdata_old ]
              then
              diff -u /tmp/userdata /var/backups/userdata_old >> /var/backups/userdata_diff.log
              if [ ! -s /var/backups/userdata_diff.log ]
              then
                     rm -f /tmp/userdata
              else
                     chattr -a /var/backups/userdata_old
                     rm -f /var/backups/userdata_old
                     echo "Executing userdata..."
                     sh /tmp/userdata > /tmp/userdata.log
                     echo "Execution of userdata script is done"
                     mv -f /tmp/userdata /var/backups/userdata_old
                     chattr +a /var/backups/userdata_old
              fi
              rm /var/backups/userdata_diff.log
              else
              echo "Executing userdata..."
              sh /tmp/userdata > /tmp/userdata.log
              echo "Execution of userdata script is done"
              mv -f /tmp/userdata /var/backups/userdata_old
              chattr +a /var/backups/userdata_old
              fi
       fi
done

#rm -rf /etc/init.d/userdataExecutor
